name: 03-workflow Runner
on: push
jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
                  echo "This job is running on an Ubuntu runner"
                  echo "Runner os is $RUNNER_OS"
              #   uname -a
              #   cat /etc/os-release
              #test
    windows-echo:
        runs-on: windows-latest
        steps:
            - name: Show OS
              shell: bash
              run: |
                  echo "This job is running on a Windows runner"
                  echo "Runner os is $RUNNER_OS"
            - name: Show OS
              shell: cmd
              run: |
                  ver
    mac-echo:
        runs-on: macos-latest
        steps:
            - name: Show OS
              run: |
                  echo "This job is running on a MacOS runner"
                  echo "Runner os is $RUNNER_OS"
              #   sw_vers
