name: Reusable

on:
    workflow_call:
        inputs:
            test-input-variable:
                # required: true
                type: string
                default: "Github Action"

jobs:
    reusable_workflow_job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hi i am  ${{ inputs.test-input-variable }}"
