name: workflow-run
on:
    workflow_run:
        workflows: [repo-event]
        types: [completed]
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: workflow run
              run: |
                  echo "Running workflow event after repo-event workflow is completed"
                  echo "Workflow run triggered by: ${{ github.event.workflow_run.trigger.actor }}"
                  echo "Workflow run status: ${{ github.event.workflow_run.status }}"
                  echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
                  echo "Workflow run ID: ${{ github.event.workflow_run.id }}"
                  echo "Workflow run URL: ${{ github.event.workflow_run.html_url }}"
